### ISSUE TITLE
Play Map Action

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/survive-the-night-sim#1]
We need to create a **play map action**, which would be a **convex action** invoking OpenAI. This action should:

- Accept the following parameters:
  - `map: number[][]`
  - `mapId`
  - `level`
  
- Call OpenAI with a prompt asking it to **play the game**.

- Use the **JSON response format**.

- Attempt to invoke a mutation to store all relevant information about:
  - Where the AI **placed the player**.
  - Where the AI **placed the boxes**.
  - Why did the AI choose these locations

**Comment by Ashutoshbind15** [comment]
on it!
