### ISSUE TITLE
Codify Game Rules

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [webdevcody/survive-the-night-sim#102]
Idea is to create a whole new page just for the game rules.

This will help in a lot of different ways:

Pros:
- New users and contributors will understand it way quicker
- Easier identification of bugs if you are not sure if something is a bug or a feature.
- Easier in development if goals and objectives are defined.
- We will move safer in development.
- We need to codify them anyways for the AI model this would just be another place to write them down.

But would also have some downsides:

Cons:
- More work: If you add something on purpose you have to put it in the rules too. 
- Slower iteration because if we want to change something we always need to decide if we want to change the game rules.
- We will move way slower in development.
- We need to keep the rules that we give the AI and the ones on the frontend / on the page in sync

The discussion seems similar to the discussion around testing (as testing slows your iteration cycle down but makes everything more safe) 

Because of the last pro argument I personally think we should add this page but let me know your thoughts on this.

**Comment by edinstance** [comment]
Forgot to comment but ive picked this up. Discord - edinstance
