### ISSUE TITLE
Mobile friendly

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/survive-the-night-sim#103]
Right now the header is a mess on mobile. Please go through each page and verify it looks well on mobile.  Also we should use a mobile menu bar for the header.

Also we need to use a drop-down menu for all admin functionality in the header.  There are too many links

**Comment by Geen-19** [comment]
I would like to work on this responsivity issue in all mobiles!

**Comment by delasy** [comment]
this was fixed in https://github.com/webdevcody/survive-the-night-sim/commit/418a98992a5b038bfcd422ac6f665c3b2da775da
