### ISSUE TITLE
globalranking and levelrankings should be renamed

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/survive-the-night-sim#104]
<img width="303" alt="Screenshot 2024-10-19 at 10 02 07 AM" src="https://github.com/user-attachments/assets/bdb6d463-dac7-46fa-ad68-1e795387463c">

To follow our convention, globalranking and levelrankings should be globalRankings and levelRankings.

**Comment by edinstance** [comment]
Hey I'd like to pick this up, discord - edinstance
