### ISSUE TITLE
Ugly scroll bar in header

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [webdevcody/survive-the-night-sim#109]
You can't see it in prod because it is not up to date due to a deployment issue. You can only see it if you run the project yourself.

<img width="1367" alt="Screenshot 2024-10-20 alle 1 49 47 PM" src="https://github.com/user-attachments/assets/a02967e0-575f-4408-a464-3262c713f5b8">
<img width="744" alt="Screenshot 2024-10-20 alle 1 50 10 PM" src="https://github.com/user-attachments/assets/da85b901-2466-472f-b34d-4f92b087f285">

**Comment by delasy** [comment]
this was fixed in https://github.com/webdevcody/survive-the-night-sim/commit/755c4f4048d3a99468a38b7ca26c949afe52fda8
