### ISSUE TITLE
Map List Page & View Map

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/survive-the-night-sim#11]
Display a page which allows a user to click through all of the maps.  For right now, the work involved would be something like this

- add a new page.tsx at /app/maps/page.tsx
- have that fetch all the maps from a convex query getMaps
- display all the maps on the UI
- display the maps in cards with a play button, after clicking play, navigate to /app/maps/[mapId]/page.tsx
- display the map on this page using the Map component

**Comment by bmonish** [comment]
@webdevcody Can I give this a try?

**Comment by webdevcody** [comment]
@bmonish what is your discord handle?

**Comment by bmonish** [comment]
@webdevcody Do you want the Maps to be added to the Menu Bar?

**Comment by webdevcody** [comment]
@bmonish I this it's all good as is, good work!

**Comment by bmonish** [comment]
@webdevcody Oh okay. I do have the code ready just in case if you need it.
