### ISSUE TITLE
Review Page - Delete and Play Maps

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/survive-the-night-sim#112]
<img width="1498" alt="Screenshot 2024-10-21 at 11 35 47 AM" src="https://github.com/user-attachments/assets/667482ea-867d-49b1-84c0-6d6e874bb9bd">

As an admin, I need a way to delete uploaded maps if they suck, and also a way to play them myself before I approve them.

**Comment by delasy** [comment]
should be fixed in https://github.com/webdevcody/survive-the-night-sim/commit/3718613e2623de4ebc7e89b70fc787e133c6be53 and https://github.com/webdevcody/survive-the-night-sim/commit/15cd47e3d755122ce81f749067c0bca2984c5230
