### ISSUE TITLE
Ratelimiter for submitting maps

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [webdevcody/survive-the-night-sim#118]
we should add a ratelimiter for submitting maps so nobody can spam maps to our admins.

I think this got really easy to implement with the release of this Convex Component: https://www.convex.dev/components/rate-limiter

**Comment by Geen-19** [comment]
I would like to work on this rate limiting feature!

**Comment by Geen-19** [comment]
what should be the limit that I should be setting up? what rate/minute or rate/second should I keep?

**Comment by webdevcody** [comment]
@Geen-19 maybe 3 a minute max

**Comment by FleetAdmiralJakob** [comment]
Nice, any other questions @Geen-19? Otherwise, I think @webdevcody you can assign the issue to him, I will solve other issues

**Comment by Geen-19** [comment]
No more questions, I will do the needful.

**Comment by FleetAdmiralJakob** [comment]
Awesome. Otherwise, if you have any questions don't hesitate to ask here or on Discord. What's your username there?

**Comment by Geen-19** [comment]
Geen_19#1126 is my username
