### ISSUE TITLE
Leaderboard Component

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/survive-the-night-sim#12]
Creating a react component which will display the score of the AI models from best to worst for a particular map.  This component should take in a mapId from props and probably call a getLeaderboard() query in convex.  The query in convex should probably figure out how to lookup the scores on the maps table, lookup the modelId & name from the models table, and display them in a sorted table.

**Comment by eliefrancois** [comment]
Hey! would like to try this out. Working through clone and playing around w the project now

**Comment by webdevcody** [comment]
@eliefrancois are you on discord? what's your handle?  also what's the status on this?
