### ISSUE TITLE
Ability for users to delete accounts

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/survive-the-night-sim#131]
A user should be able to delete their account.  Add a "Settings" in a dropdown menu which takes them to a page where they can delete their account with a confirmation dialog.

this should delete their user and any data associated with them.  Do not delete any maps they uploaded, instead just empty out the userId.  You can delete any results or scores they have.

**Comment by edinstance** [comment]
I'll pick this up! Discord - edinstance
