### ISSUE TITLE
React Performance Optimisation

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [webdevcody/survive-the-night-sim#138]
We should probably update a few dependency arrays and add a few useCallbacks or adopt the React Compiler ig.

<img width="1032" alt="image" src="https://github.com/user-attachments/assets/46022e17-60e7-453d-9127-6ee4c9a0676c">

Example is from the `Visualizer` component

<img width="1336" alt="image" src="https://github.com/user-attachments/assets/ca6fcf7f-36b2-4214-9ab7-eb1e9a6df74f">

PS: I don't know anything about React Performance Optimisation I just found these ESLint warnings

**Comment by delasy** [comment]
the reason why these are warnings is because it's not applicable in all cases, we are aware of these warnings and everything works as expected
