### ISSUE TITLE
Header on Mobile is under cards

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [webdevcody/survive-the-night-sim#140]
<img width="643" alt="image" src="https://github.com/user-attachments/assets/b559aaa2-0064-4179-8ac2-f53f52ec193e">

I would fix this issue by setting the z-index of the header way higher

**Comment by edinstance** [comment]
For me this is fine, can anyone else reproduce this?

<img width="569" alt="Screenshot 2024-11-02 at 11 53 28" src="https://github.com/user-attachments/assets/eb4c4b19-8144-4f38-9f25-ba8d28588230">

**Comment by FleetAdmiralJakob** [comment]
> For me this is fine, can anyone else reproduce this?
> 
> <img alt="Screenshot 2024-11-02 at 11 53 28" width="569" src="https://private-user-images.githubusercontent.com/71530287/382469042-eb4c4b19-8144-4f38-9f25-ba8d28588230.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NDk3MzEsIm5iZiI6MTczMDU0OTQzMSwicGF0aCI6Ii83MTUzMDI4Ny8zODI0NjkwNDItZWI0YzRiMTktODE0NC00ZjM4LTlmMjUtYmE4ZDI4NTg4MjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDEyMTAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyZGRhNzhiZDdmNmFhMzI4YzJhODY1ZTRiNGZmYjRkZGE5YTg5MTAxY2FmZDdmMzFmODcxZDY4NmM1ZDg5YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L1s0wNqEHb3unZGuQR2bI8nLvDTiKbH31NdbBHDtMew">

@edinstance Can you go to the /play page?

**Comment by edinstance** [comment]
@FleetAdmiralJakob Didn't see that, good spot
