### ISSUE TITLE
Can't "run model" with the mock flag enabled

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [webdevcody/survive-the-night-sim#142]
If I press "test model" with the mock model flag set to true, I get this weird error, and the games are in a "game is playing" mode forever. Can anyone confirm this behaviour? 

![image](https://github.com/user-attachments/assets/988e5475-551b-46eb-bb48-70e1096effe9)
![image](https://github.com/user-attachments/assets/1037b03a-bf59-4fc5-b831-2883ed2aaf88)

**Comment by delasy** [comment]
fixed in https://github.com/webdevcody/survive-the-night-sim/commit/9886c4715433d08d16b94f20c6453a71e84efb05
