### ISSUE TITLE
New Game Mutation

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/survive-the-night-sim#2]
Create a internal convex mutation which we can invoke from the convex dashboard to have it create a new game schema

- create a game schema to track the ai model id and game id
- create a map schema which holds an initial board, and level.  level needs to be an index
- when the internalMutation is invoked, create a new game record
- run an intenral convex action called playMapAction and pass the first map (level = 1), gameId to the action
- create a blank score record in a "scores" table (create the scores table) with an initial score of 0

see scores table in diagram

![image](https://github.com/user-attachments/assets/472253fb-00af-4754-806e-b39ba8aad415)

**Comment by omerfe** [comment]
I'm up!
