### ISSUE TITLE
Add in Claude

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/survive-the-night-sim#22]
add in the ability to use claude for the ai model

**Comment by Ashutoshbind15** [comment]
hey, kindly assign

**Comment by krishkalaria12** [comment]
Hey, i have added the claude 3.5 model for it

**Comment by krishkalaria12** [comment]
https://github.com/webdevcody/survive-the-night-sim/pull/36
Added the claude 3.5 sonnet and opened a PR for it 
there may be some error handling required for it
