### ISSUE TITLE
Ability to users to upload their own maps

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/survive-the-night-sim#24]
It might be cool if a user could upload their own maps and that would be added to the rotation.

**Comment by edinstance** [comment]
I'm happy to pick this up, Just wondering what format the map that the user brings, e.g. would it be a json file like
`{
    "level": 1,
    "width": 8,
    "height": 8,
    "grid": [
        [],
        []
    ]
}`

**Comment by Ashutoshbind15** [comment]
@edinstance the user could just bring in a 2d array of strings, as the rest is taken care of in the Simulator Constructor

https://github.com/webdevcody/survive-the-night-sim/blob/eaf49713c3cfa24703d6fe67bbb45c4d9982e122/simulators/zombie-survival/ZombieSurvival.ts#L20

**Comment by edinstance** [comment]
Thank you so much @Ashutoshbind15. 

Unfortunately I won't be able to pick this issue up anymore so if anyone wants it please take it.

**Comment by jaspal007** [comment]
@Ashutoshbind15 how about create an interactive grid where user can enter the characters as in the grid giving them the ability to place zombies and stones as the way it's going to be in the final output. 
As for the string we can map the input with its specific coordinates.
If this aligns with your goal. I'm happy to take up this task.

**Comment by delasy** [comment]
@jaspal007
the idea here is to show maps in database and give user ability to upload custom maps.

**Comment by jaspal007** [comment]
Understood. 
One more thing, is the custom map added needs to be stored in database under the specific user who created it so that only he can access them or they will be available to all the users?

**Comment by webdevcody** [comment]
@jaspal007 are you on discord? I'm not allowing contributors unless you are active on the discord

**Comment by jaspal007** [comment]
yes! I am on discord username: mike007
