### ISSUE TITLE
Text is not visible in light mode

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [webdevcody/survive-the-night-sim#28]
<img width="1379" alt="image" src="https://github.com/user-attachments/assets/90aa73ac-5dc1-4ca2-a343-b8404c0de9aa">

2 solutions: 

1. Only one theme, text is not changing for light mode
2. 2 themes everything changes for light mode

**Comment by jaspal007** [comment]
Hi! I would like to take up this task to refine the CSS for light mode as well.

**Comment by FleetAdmiralJakob** [comment]
Ok nice @jaspal007 go for it! Which of the two options will u try to implement?

**Comment by jaspal007** [comment]
I am inclined more towards the **second option;** creating a theme custom to light mode.
I am going to use the ThemeToggle component from the component folder to allow user to switch the theme according to their requirements or as per the device configuration.
<img width="1437" alt="image" src="https://github.com/user-attachments/assets/542d1a74-83a2-4062-84a6-6f94529ad268">
