### ISSUE TITLE
Game Sprites

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/survive-the-night-sim#3]
We need a way to visualize the game 2d game board with sprites

we need the following transparent images / sprits:

- player
- box
- empty cell
- zombie
- rock (or could be a card, rubbish, something impassible)

**Comment by bymrbanks** [comment]
Ready to go! @webdevcody

**Comment by bymrbanks** [comment]
![character-sprites_001](https://github.com/user-attachments/assets/151cb552-9bbc-4756-af55-8262f82f893d)

Player and Zombie @webdevcody
