### ISSUE TITLE
Run SImulation Function

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/survive-the-night-sim#4]
We will need a function which runs the simulation of the game.  It should do the following

- take in the map
- each turn, make the player shoot at the closest zombie
- next, each zombie, (looping over top left to bottom left to keep it deterministic), will move 1 step foward towards the player
- if a zombie moves into the player, end the game
- if a zombie tries to move onto a rock, it'll find the next path path to get to the player
- if player kills all zombies, end the game
- if a zombie tries to move into a box, damage the box
- a box has 2 health
- remove the box from the map when box is destroyed
- zombie have 2 health

**Comment by delasy** [comment]
sounds like fun
