### ISSUE TITLE
Add claude's model and perplexity with llama to the list of curated ai models

### ISSUE THREAD

**Issue by krishkalaria12** [webdevcody/survive-the-night-sim#46]
Add claude's and perplexity with llama model for the game simulation

**Comment by krishkalaria12** [comment]
Working on it 🚀! Can you assign it @webdevcody

**Comment by delasy** [comment]
@krishkalaria12 what is your discord username?

<img width="899" alt="image" src="https://github.com/user-attachments/assets/9a76ec59-a106-40b0-a347-c6f8e6d2b104">

**Comment by krishkalaria12** [comment]
Completely forgot about mentioning my discord username 
i have edited the issue and also 
discord username - krishkalaria12

**Comment by webdevcody** [comment]
sounds good

**Comment by krishkalaria12** [comment]
I have added the pull request for the models 
there may be some errors but i have tried my best debugging them all
[Added claude and perplexity ](https://github.com/webdevcody/survive-the-night-sim/pull/62)

**Comment by webdevcody** [comment]
closing issue, models were added, but they both don't seem to work successfully yet
