### ISSUE TITLE
Cheat: Ways to place more than two blocks

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [webdevcody/survive-the-night-sim#60]
Place player and two blocks -> run simulation -> retry it -> do it again all steps again -> you can set two more blocks with the old blocks not removed

<img width="453" alt="image" src="https://github.com/user-attachments/assets/fd422802-481d-456a-9eb8-7cb6cff82605">

https://github.com/user-attachments/assets/4ce11c29-2d12-4587-9a46-d5d1ae2b9bc7

**Comment by edinstance** [comment]
I'd like to pick this up!! Discord - edinstance
