### ISSUE TITLE
Error when trying to run perlexity

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/survive-the-night-sim#65]
<img width="976" alt="Screenshot 2024-10-17 at 10 29 49 AM" src="https://github.com/user-attachments/assets/94ad1529-c942-4a3f-91e3-85d842eb6339">

**Comment by webdevcody** [comment]
@krishkalaria12 I'm getting this when trying to run the code

**Comment by krishkalaria12** [comment]
looking onto it

**Comment by krishkalaria12** [comment]
I found the issue 
it seems perplexity doesn't allow 2 user prompts together so i have merged both the prompt and the map in one single user based role prompt and sent it and also switched from axios to fetch
@webdevcody

**Comment by webdevcody** [comment]
@krishkalaria12 both of the models seem to fail when I run it.  Is this working for you when you test it? <img width="1397" alt="Screenshot 2024-10-17 at 2 15 28 PM" src="https://github.com/user-attachments/assets/1ddee960-4a7a-481f-89a9-b261b0b93169">

**Comment by delasy** [comment]
fixed in https://github.com/webdevcody/survive-the-night-sim/commit/328c8890ab9859c095f609137faa695ded3efaa0
