### ISSUE TITLE
Error when trying to run claude sonnet

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/survive-the-night-sim#66]
<img width="1060" alt="Screenshot 2024-10-17 at 10 38 17 AM" src="https://github.com/user-attachments/assets/4ae272da-c7d8-4d24-b0c5-060ecacfb4a1">

**Comment by webdevcody** [comment]
@krishkalaria12 I'm getting this when trying to run the code

**Comment by krishkalaria12** [comment]
looking onto it

**Comment by krishkalaria12** [comment]
i had mis spelled the claude model name 
it should have been claude-3-5-sonnet-20240620

**Comment by webdevcody** [comment]
this also seems to still be failing but for new reasons.  Is this working for you when you test?

<img width="1428" alt="Screenshot 2024-10-17 at 2 16 00 PM" src="https://github.com/user-attachments/assets/986b4f2f-99e3-4c42-a18e-9d94edc68966">

**Comment by delasy** [comment]
Was fixed in 93739808cec31db40dd88d7f82481070b32190e1
