### ISSUE TITLE
Need example maps

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/survive-the-night-sim#7]
We need someone to design 5 example initial maps we could use in this game.

They can be whatever size you think is necessary, but I'd say start by keeping them smaller, such as 5x5, 7x7, or 11x11.

We'll add functionality later to allow players to test the maps, but for now, we just need some hard coded arrays.

Remember the map is string[][], and only has the following characters

- "P" Player
- "Z" Zombie
- "B" Block
- "R" Rock
- " " Empty

**Comment by florianheysen** [comment]
I can take care of that!

**Comment by florianheysen** [comment]
Here are the boards I've selected, with a brief explanation of the placements. 

_Note: player and boxes placement can be removed if the player has to place them manually._

---

### **Game Board 1**
The player is in the bottom-left corner, protected by a block on their left and in front. Zombies approach from the top-left and bottom-right, with rocks forcing zombies to take longer paths to reach the player.
```javascript
const gameBoard1 = [
    ["Z", "", "", "R", ""],
    ["B", "R", "", "", ""],
    ["", "", "", "", ""],
    ["", "", "", "B", "Z"],
    ["P", "", "", "", ""],
];
```

---

### **Game Board 2**
The player is positioned at the bottom-center of the board, with two blocks in front for protection. Zombies are coming from the top-right and bottom-left, and the rocks slow their advance.
```javascript
const gameBoard2 = [
    ["", "", "R", "", "Z"],
    ["", "", "", "", ""],
    ["", "", "", "R", ""],
    ["Z", "", "", "", ""],
    ["", "B", "P", "B", ""],
];
```

---

### **Game Board 3**
The player is located in the bottom-left corner, boxed in between two blocks and a rock. This placement theoretically prevents zombies from reaching the player.
```javascript
const gameBoard3 = [
    ["Z", "", "", "R", "", "", ""],
    ["", "", "", "", "", "", ""],
    ["", "", "", "", "", "", ""],
    ["", "", "", "", "", "Z", ""],
    ["", "", "", "", "", "", ""],
    ["", "R", "", "", "", "", ""],
    ["B", "P", "B", "", "R", "", ""],
];
```
---

### **Game Board 4**
The player is positioned toward the bottom-left with two blocks offering protection. Zombies approach from the top-left and bottom-right, and the rocks slow their advances from different angles.
```javascript
const gameBoard4 = [
    ["", "Z", "", "", "R", "", ""],
    ["", "", "", "", "", "", ""],
    ["", "", "", "", "", "", ""],
    ["", "", "", "", "", "", "Z"],
    ["", "", "R", "", "", "", ""],
    ["", "B", "P", "B", "", "", ""],
    ["", "", "", "", "", "", ""],
];
```
---

### **Game Board 5**
The player is positioned near the center-right of the board with a zombie directly to the left. Zombies are spread across the board, approaching from various angles, but rocks and blocks offer strategic barriers.
```javascript
const gameBoard5 = [
    ["", "", "", "P", "R", "Z", "", "", "", "", ""],
    ["", "", "", "B", "", "", "", "", "", "", ""],
    ["Z", "", "", "B", "", "R", "", "", "", "", ""],
    ["", "", "", "", "", "", "", "", "", "", ""],
    ["", "", "", "", "R", "", "", "", "", "Z", ""],
    ["", "", "", "", "", "", "", "", "", "", ""],
    ["", "", "R", "", "", "", "", "", "", "", ""],
    ["", "", "", "", "", "", "Z", "", "", "", ""],
    ["B", "", "", "", "", "", "", "", "", "", ""],
    ["", "", "", "", "", "", "", "", "", "", ""],
    ["Z", "", "", "", "Z", "", "", "", "", "", "Z"],
];
```

@webdevcody Please let me know if I can create a seed file to get them in convex.
