### ISSUE TITLE
Prompt Versioning

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/survive-the-night-sim#70]
I think a way to store the prompt in a "prompts" table would be useful.  Then when the scores for the AI are updated, scope them based on the promptId.  As an admin, we should have a way to easily modify prompts and set them as active.  so the prompt table might have a  prompt isActive boolean then load the active prompt when these AI games start and be sure when scores are stored, scope them by promptId

**Comment by edinstance** [comment]
I'd like to pick this up! Discord - edinstance
