### ISSUE TITLE
Track token use per play

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/survive-the-night-sim#71]
It might be interesting to track how many token's an AI model uses when playing a round so that we can then display a cost / game won or "brain efficiency" that we can then display on the leaderboard

**Comment by FleetAdmiralJakob** [comment]
input and output or only output tokens?

**Comment by delasy** [comment]
@FleetAdmiralJakob the idea is to know how much you spend per one click of "Start game"

**Comment by OpeOginni** [comment]
I want to work on this 

discord: obo.baddest

**Comment by OpeOginni** [comment]
Made a PR for this issue if anyone can check it out and give feedback.

https://github.com/webdevcody/survive-the-night-sim/pull/134

Thank you.

**Comment by delasy** [comment]
closed in https://github.com/webdevcody/survive-the-night-sim/pull/134
