### ISSUE TITLE
Setup Dockerfile to deploy next to Railway

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/survive-the-night-sim#8]
checkout out my starter kit for code examples https://github.com/webdevcody/wdc-saas-starter-kit

basically we just need the Dockerfile, and modify the next.config to allow stand alone.  Try to get it deployed to your own railway service, and if it's all good, make a pull request and I'll get it hooked to my own railway env.

**Comment by edinstance** [comment]
Hey I'd like to pickup this issue!
