### ISSUE TITLE
IsAdmin Util

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/survive-the-night-sim#83]
<img width="554" alt="Screenshot 2024-10-18 at 8 48 53 AM" src="https://github.com/user-attachments/assets/ffe3b17a-d31a-48ed-9154-9f2bf515d648">

We need a helper function for admin only mutations and queries.  checkout https://github.com/get-convex/convex-helpers/blob/main/packages/convex-helpers/README.md#custom-functions make a custom query and mutation

**Comment by Ashutoshbind15** [comment]
on it
