### ISSUE TITLE
admin's schema index

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/survive-the-night-sim#84]
The admin's table should have an index by userId and all code should be using .withindex to check if a user is an admin.

<img width="652" alt="Screenshot 2024-10-18 at 8 52 29 AM" src="https://github.com/user-attachments/assets/59c57af9-23d2-4b8d-ac4d-dd97fad81be9">

^ e.g. don't do this

**Comment by Ashutoshbind15** [comment]
on it!
