### ISSUE TITLE
[Improvement] Scroll on the homepage is janky

### ISSUE THREAD

**Issue by Darialyphia** [webdevcody/survive-the-night-sim#88]
Scrolling the home page on list of games seems to have degraded performance as the scroll is very laggy.

A quick test with chrome's performance profiler reveals a lot of dropped frames due to GPU work taking too ling 
![Screenshot 2024-10-18 170455](https://github.com/user-attachments/assets/94cd625c-611e-421e-838d-f4751969173e)

**Comment by delasy** [comment]
should be fixed now
