### ISSUE TITLE
Play Page

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/survive-the-night-sim#89]
<img width="1419" alt="Screenshot 2024-10-18 at 11 07 38 AM" src="https://github.com/user-attachments/assets/0c91bd15-c8fa-42fe-b534-026971d7454b">

We should add placeholders for if the user has won every level and add a button for them to "upload a map"

**Comment by delasy** [comment]
fixed in https://github.com/webdevcody/survive-the-night-sim/commit/5baa778901640d02e266dc247c903dcfbeb64a81
