### ISSUE TITLE
Save round Mutation

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/survive-the-night-sim#9]
![image](https://github.com/user-attachments/assets/04fff057-3c83-4d65-a21a-de0e5a54605f)

We need a saveRoundMutation which will take the result of the ai playing the map, and store it in a "results" table.  Please see the diagram, but in all we need to track.  These will be passed in as args.

- reasoning
- gameId
- level
- isWin

also, if the game was a win, increment a score in a 'scores' table for the modelId associated with the game.  Query for the game record to figure out the modelId, then increment the score for that game in the scores table.

**Comment by webdevcody** [comment]
@Geen-19 yes all backend is using convex

**Comment by Geen-19** [comment]
Okay, add me in!
