### ISSUE TITLE
Maps - Ability to Change Max Blocks and Landmines

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/survive-the-night-sim#96]
To make the game more interesting, we should allow the game and map maker to be able to set the max blocks a user is allowed to set.  This would also mean the prompt we pass to AI much be dynamic in regards to the "max blocks" logic.

**Comment by FleetAdmiralJakob** [comment]
So if I understand you correctly you want both:

- Ability for the map maker to change the default max amount of blocks

- And an ability for users to change the amount of blocks they could use

With the latter one we should consider that the players that "beat" the map with more blocks shouldnt be included in the list of players that bet a level as everyone can beat a level if he spams the map full of blocks

**Comment by webdevcody** [comment]
basically add a "maxBlocks" number to the map schema and then set it all to default to 2, but if it's 3, then allow for placing 3 blocks, etc.  I think they would still be included in the list if they beat the level.  The level would be designed with how to strategically use the blocks to win.

**Comment by MZT7** [comment]
Can i work on this

**Comment by delasy** [comment]
@MZT7 sure, go ahead

**Comment by MZT7** [comment]
> basically add a "maxBlocks" number to the map schema and then set it all to default to 2, but if it's 3, then allow for placing 3 blocks, etc. I think they would still be included in the list if they beat the level. The level would be designed with how to strategically use the blocks to win.

I have added maxBlocks to the map schema and set 2 as the default value. Can you clarify the rest

**Comment by delasy** [comment]
> I have added maxBlocks to the map schema and set 2 as the default value. Can you clarify the rest

on the pages Play and Playground it's hardcoded to have 2 blocks and one landmine. You need to make these numbers dynamic. In simulator exactly same thing, need to pass in max number of blocks/landmines allowed as options. When generating prompt for AI it should tell exact numbers in the prompt generated.

**Comment by MZT7** [comment]
@delasy  Have sent a pull request

**Comment by delasy** [comment]
implemented in https://github.com/webdevcody/survive-the-night-sim/pull/144
